# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - windows
  # - osx

julia:
  # - 1.0
  # - 1.2
  - 1.5

notifications:
  email: false

addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib

script:
  - julia test/deps.jl
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  allow_failures:
    - os: windows
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    pkg"dev ."'
        - julia --project=docs/ docs/make.jl
      after_success: skip
